import { Inter } from 'next/font/google'
import Navbar from '@/components/NavbarOld'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Login - TechGenius',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
        {children}
    </>
  )
}
